export enum NotificationType {
  AGREEMENT_PENDING_REVIEW = "AGREEMENT_PENDING_REVIEW",
  AGREEMENT_ACCEPTED = "AGREEMENT_ACCEPTED",
  AGREEMENT_REJECTED = "AGREEMENT_REJECTED",
  AGREEMENT_COUNTEROFFER = "AGREEMENT_COUNTEROFFER",
  BLOCKADE_SUSPENDED = "BLOCKADE_SUSPENDED",
  BLOCKADE_REACTIVATED = "BLOCKADE_REACTIVATED",
  GENERIC = "GENERIC",
}
