export enum AppAction {
  CREATE_COLLECTION = "CREATE_COLLECTION",
  BLOK_CHECK = "BLOK_CHECK",
  CREATE_PAYMENT = "CREATE_PAYMENT",
  VIEW_DASHBOARD = "VIEW_DASHBOARD",
  TRANSFER_TO_LAWYER = "TRANSFER_TO_LAWYER",
  MANAGE_GOP = "MANAGE_GOP",
  CANCEL_GOP = "CANCEL_GOP",
  START_COP = "START_COP",
}