export enum AgreementStatus {
  PENDING = "PENDING",
  IN_NEGOTIATION = "IN_NEGOTIATION",
  COUNTEROFFER = "COUNTEROFFER",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED",
  CLOSED = "CLOSED",
}
